trigger:
- main  # Pipeline triggers on changes in the main branch

# Use a self-hosted agent running on your local machine
pool:
  name: 'SQLTest'  # Replace with the name of your self-hosted agent pool

variables:
  sqlServerInstance: 'SWG_APXUPEG1GUJ\SQLEXPRESS'  # Local SQL Server instance
  databaseName: 'Jarvis'                          # Database to export
  bacpacPath: 'C:\output\Jarvis.bacpac'           # Local path for the bacpac file
  sqlUsername: 'sa'                # SQL Server username
  sqlPassword: 'Aksh@123'                # SQL Server password

steps:
# Step 1: Export BACPAC using SqlPackage
- script: |
    set PATH=C:\SQL\sqlpackage;%PATH%
    SqlPackage.exe /Action:Export `
                   /SourceServerName:"$(sqlServerInstance)" `
                   /SourceDatabaseName:"$(databaseName)" `
                   /TargetFile:"$(bacpacPath)" `
                   /SourceUser:"$(sqlUsername)" `
                   /SourcePassword:"$(sqlPassword)"

# Optional: Verify the BACPAC file exists locally
- script: |
    dir C:\output
  displayName: 'Verify BACPAC File Locally'
