trigger:
- main  # Pipeline triggers on changes in the main branch

pool:
  vmImage: 'windows-latest'  # Use a Windows-based agent

variables:
  sqlServerInstance: 'SWG_APXUPEG1GUJ\SQLEXPRESS'  # Local SQL Server instance
  databaseName: 'Jarvis'                          # Database to export
  bacpacPath: '$(Build.ArtifactStagingDirectory)/Jarvis.bacpac'  # Output path for bacpac file
  sqlUsername: 'sa'                # SQL Server username
  sqlPassword: 'Aksh@123'                # SQL Server password

steps:
# Step 1: Download and Install SqlPackage Utility
- script: |
    echo "Downloading SqlPackage..."
    Invoke-WebRequest -Uri "https://aka.ms/sqlpackage-windows" -OutFile "sqlpackage.zip"
    echo "Extracting SqlPackage..."
    Expand-Archive -Path "sqlpackage.zip" -DestinationPath "$(Build.SourcesDirectory)/sqlpackage"
    echo "SqlPackage downloaded and extracted."
  displayName: 'Download and Install SqlPackage'

# Step 2: Export BACPAC using SqlPackage
- script: |
    echo "Starting BACPAC export for database: $(databaseName)"
    "$(Build.SourcesDirectory)/sqlpackage/sqlpackage/SqlPackage.exe" /Action:Export `
                   /SourceServerName:"$(sqlServerInstance)" `
                   /SourceDatabaseName:"$(databaseName)" `
                   /TargetFile:"$(bacpacPath)" `
                   /SourceUser:"$(sqlUsername)" `
                   /SourcePassword:"$(sqlPassword)"
  displayName: 'Export Database to BACPAC'

# Step 3: Publish the BACPAC as a pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BACPAC'
    publishLocation: 'Container'
  displayName: 'Publish BACPAC File'
